#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org
START=60
STOP=60

start() {
	/usr/bin/russconnectd -d -i 127.0.0.1:16012 -l 16011 -a 10/1/0 -z 6 -u local:/tmp/eib
}

stop() {
	kill $(cat /var/run/russconnectd.pid)
}

